<a href="https://colab.research.google.com/github/sanjay-MGR/Machine-Learning-basic-/blob/main/Hyperparameter_turing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import laiberies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#loaddataset
data = sns.load_dataset('tips')

In [ ]:
data.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
data.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
#encode
enc_sex = ({'Male':1,'Female':0})
enc_smoker = ({'Yes':1,'No':0})
enc_time = ({'Lunch':0,'Dinner':1})
enc_day =({'Thur':0,'Fri':1,'Sat':2,'Sun':3})

In [ ]:
data['sex']=data['sex'].map(enc_sex)
data['smoker']=data['smoker'].map(enc_smoker)
data['time']=data['time'].map(enc_time)
data['day']=data['day'].map(enc_day)

In [ ]:
data.head(2)

   total_bill   tip sex smoker day time  size
0       16.99  1.01   0      0   3    1     2
1       10.34  1.66   1      0   3    1     3

In [ ]:
#split data into x and y
x = data.drop('day',axis = 1)
y = data['day']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 42 )

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
#model build
model = DecisionTreeRegressor()
model

DecisionTreeRegressor()

In [ ]:
#fit the model
model.fit(x_train,y_train)

DecisionTreeRegressor()

In [ ]:
#predict the value
y_pred = model.predict(x_train)
y_pred

array([2., 2., 1., 3., 0., 3., 0., 3., 2., 3., 2., 3., 3., 3., 1., 2., 2.,
       2., 2., 2., 3., 3., 2., 0., 2., 2., 2., 3., 3., 2., 0., 0., 3., 2.,
       0., 2., 3., 2., 3., 2., 2., 3., 2., 0., 1., 3., 3., 1., 0., 0., 2.,
       3., 2., 1., 0., 0., 2., 2., 2., 3., 0., 3., 3., 0., 3., 1., 0., 0.,
       3., 1., 0., 2., 3., 1., 2., 0., 2., 2., 0., 3., 0., 3., 2., 2., 3.,
       3., 0., 2., 0., 3., 0., 2., 0., 0., 1., 3., 2., 0., 2., 3., 2., 2.,
       0., 2., 3., 3., 0., 2., 0., 3., 1., 3., 3., 0., 3., 3., 2., 3., 0.,
       1., 2., 1., 3., 3., 0., 2., 0., 3., 2., 2., 1., 0., 2., 1., 0., 3.,
       3., 2., 2., 0., 3., 3., 2., 2., 0., 0., 1., 2., 3., 2., 3., 2., 3.,
       2., 3., 2., 2., 2., 2., 3., 0., 2., 2., 0., 3., 2., 3., 0., 0., 2.,
       3., 2., 3., 3., 0., 0., 3., 2., 1., 3., 0., 0., 2., 2., 2., 0., 0.,
       2., 3., 2., 2., 3., 1., 3., 2.])

In [ ]:
y_pred_test = model.predict(x_test)
y_pred_test

array([2., 2., 3., 2., 0., 3., 0., 0., 3., 2., 3., 1., 0., 2., 0., 1., 0.,
       2., 2., 0., 3., 3., 3., 1., 3., 0., 3., 3., 2., 2., 2., 1., 2., 2.,
       2., 0., 2., 0., 0., 2., 2., 0., 3., 3., 1., 1., 2., 3., 0.])

In [ ]:
#check accuracy
from sklearn.metrics import r2_score

In [ ]:
r2_train = r2_score(y_train,y_pred)
r2_train

1.0

In [ ]:
r2_test = r2_score(y_test,y_pred_test)
r2_test

0.7187141216991964

In [ ]:
# improve the model by puring the tree using GridSearchCV
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid = {
    'max_depth':[2,3,4,5,6,7,8,9],
    'min_samples_split':[2,4,10,12,16,18,24,28,38,40,45,50],
    'min_samples_leaf':[1,2,3,46,7,9,10,14,16,18,19],
    'max_leaf_nodes':[5,10,15,20,25,30,35,40,45]
}

In [ ]:
grid = GridSearchCV(estimator = model,param_grid = param_grid,cv = 5)

In [ ]:
#train the. model
grid.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'max_depth': [2, 3, 4, 5, 6, 7, 8, 9],
                         'max_leaf_nodes': [5, 10, 15, 20, 25, 30, 35, 40, 45],
                         'min_samples_leaf': [1, 2, 3, 46, 7, 9, 10, 14, 16, 18,
                                              19],
                         'min_samples_split': [2, 4, 10, 12, 16, 18, 24, 28, 38,
                                               40, 45, 50]})

In [ ]:
print(f'best parameters are =  {grid.best_params_}')

best parameters are =  {'max_depth': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'min_samples_split': 45}

In [ ]:
# build new model
model_new = DecisionTreeRegressor(max_depth = 4,max_leaf_nodes =10,min_samples_leaf=16,min_samples_split=45)

In [ ]:
model_new

DecisionTreeRegressor(max_depth=4, max_leaf_nodes=10, min_samples_leaf=16,
                      min_samples_split=45)

In [ ]:
#train the model
model_new.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=4, max_leaf_nodes=10, min_samples_leaf=16,
                      min_samples_split=45)

In [ ]:
#predict the value
y_pred_new = model_new.predict(x_train)
y_pred_new

array([2.52777778, 2.        , 2.375     , 2.76190476, 0.02857143,
       2.17857143, 0.02857143, 2.375     , 2.17857143, 2.52777778,
       2.        , 2.76190476, 2.52777778, 2.375     , 0.33333333,
       2.17857143, 2.17857143, 2.        , 2.52777778, 2.375     ,
       2.17857143, 2.76190476, 2.        , 0.02857143, 2.17857143,
       2.        , 2.76190476, 2.375     , 2.76190476, 2.        ,
       0.02857143, 0.02857143, 2.17857143, 2.17857143, 0.02857143,
       2.        , 2.52777778, 2.76190476, 2.52777778, 2.17857143,
       2.17857143, 2.52777778, 2.17857143, 0.02857143, 2.375     ,
       2.        , 2.52777778, 2.375     , 0.02857143, 0.33333333,
       2.        , 2.52777778, 2.17857143, 0.02857143, 0.02857143,
       0.02857143, 2.52777778, 2.52777778, 2.        , 2.375     ,
       0.33333333, 2.52777778, 2.17857143, 0.02857143, 2.17857143,
       2.        , 0.02857143, 0.02857143, 2.375     , 2.        ,
       0.02857143, 2.375     , 2.52777778, 2.        , 2.52777778,
       0.02857143, 2.        , 2.52777778, 0.02857143, 2.52777778,
       0.02857143, 2.76190476, 2.17857143, 2.52777778, 2.52777778,
       2.76190476, 0.02857143, 2.52777778, 0.02857143, 2.375     ,
       0.33333333, 2.        , 0.02857143, 0.02857143, 0.33333333,
       2.        , 2.52777778, 0.33333333, 2.17857143, 2.76190476,
       2.        , 2.52777778, 0.02857143, 2.76190476, 2.375     ,
       2.375     , 0.02857143, 2.17857143, 0.33333333, 2.76190476,
       2.17857143, 2.76190476, 2.52777778, 0.02857143, 2.        ,
       2.17857143, 2.        , 2.52777778, 0.02857143, 0.33333333,
       2.        , 0.33333333, 2.17857143, 2.52777778, 0.33333333,
       2.17857143, 0.33333333, 2.76190476, 2.375     , 2.52777778,
       2.17857143, 0.33333333, 2.        , 0.33333333, 0.02857143,
       2.52777778, 2.76190476, 2.76190476, 2.        , 0.02857143,
       2.52777778, 2.17857143, 2.375     , 2.52777778, 0.02857143,
       0.33333333, 0.33333333, 2.375     , 2.76190476, 2.375     ,
       2.52777778, 2.        , 2.375     , 2.76190476, 2.375     ,
       2.        , 2.        , 2.        , 2.        , 2.17857143,
       0.02857143, 2.17857143, 2.17857143, 0.33333333, 2.76190476,
       2.        , 2.        , 0.33333333, 0.02857143, 2.52777778,
       2.76190476, 2.        , 2.52777778, 2.76190476, 0.02857143,
       0.02857143, 2.52777778, 2.375     , 2.52777778, 2.76190476,
       0.02857143, 0.33333333, 2.52777778, 2.375     , 2.        ,
       0.02857143, 2.17857143, 2.17857143, 2.375     , 2.52777778,
       2.375     , 2.52777778, 2.        , 2.375     , 2.        ])

In [ ]:
y_pred_test_new = model_new.predict(x_test)
y_pred_test_new

array([2.17857143, 2.52777778, 2.76190476, 2.375     , 0.33333333,
       2.        , 0.33333333, 0.02857143, 2.52777778, 2.        ,
       2.17857143, 2.52777778, 0.02857143, 2.        , 0.02857143,
       0.02857143, 0.33333333, 2.17857143, 2.52777778, 0.02857143,
       2.76190476, 2.17857143, 2.375     , 2.52777778, 2.375     ,
       0.02857143, 2.52777778, 2.375     , 2.76190476, 2.76190476,
       2.17857143, 2.        , 2.76190476, 2.375     , 2.52777778,
       0.02857143, 2.        , 0.33333333, 0.02857143, 2.        ,
       2.52777778, 0.02857143, 2.17857143, 2.52777778, 0.33333333,
       2.        , 2.        , 2.17857143, 0.02857143])

In [ ]:
#check the accuracy
r2_train_new = r2_score(y_train,y_pred_new)
r2_train_new

0.7887454546331395

In [ ]:
r2_test_new = r2_score(y_test,y_pred_test_new)
r2_test_new

0.8330326532402093

In [ ]:
#using randomsearchcv
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
dict_param = {
    'max_depth':[2,3,4,5,6,7,8,9],
    'min_samples_split':[2,4,10,12,16,18,24,28,38,40,45,50],
    'min_samples_leaf':[1,2,3,46,7,9,10,14,16,18,19],
    'max_leaf_nodes':[5,10,15,20,25,30,35,40,45]
}

In [ ]:
random = RandomizedSearchCV(estimator = model,param_distributions = dict_param,cv = 5)

In [ ]:
#fit the model
random.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=DecisionTreeRegressor(),
                   param_distributions={'max_depth': [2, 3, 4, 5, 6, 7, 8, 9],
                                        'max_leaf_nodes': [5, 10, 15, 20, 25,
                                                           30, 35, 40, 45],
                                        'min_samples_leaf': [1, 2, 3, 46, 7, 9,
                                                             10, 14, 16, 18,
                                                             19],
                                        'min_samples_split': [2, 4, 10, 12, 16,
                                                              18, 24, 28, 38,
                                                              40, 45, 50]})

In [ ]:
#find best parameter
print(f'best parameters are = {random.best_params_}')

best parameters are = {'min_samples_split': 45, 'min_samples_leaf': 16, 'max_leaf_nodes': 35, 'max_depth': 8}

In [ ]:
#create new model with best paraameters
new_model = DecisionTreeRegressor(max_depth = 8,max_leaf_nodes = 35,min_samples_leaf = 16,min_samples_split= 45)

In [ ]:
#fit the model
new_model.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=8, max_leaf_nodes=35, min_samples_leaf=16,
                      min_samples_split=45)

In [ ]:
#predict the value
y_pred_new_new = new_model.predict(x_train)
y_pred_new_new

array([2.52777778, 2.        , 2.375     , 2.76190476, 0.02857143,
       2.17857143, 0.02857143, 2.375     , 2.17857143, 2.52777778,
       2.        , 2.76190476, 2.52777778, 2.375     , 0.33333333,
       2.17857143, 2.17857143, 2.        , 2.52777778, 2.375     ,
       2.17857143, 2.76190476, 2.        , 0.02857143, 2.17857143,
       2.        , 2.76190476, 2.375     , 2.76190476, 2.        ,
       0.02857143, 0.02857143, 2.17857143, 2.17857143, 0.02857143,
       2.        , 2.52777778, 2.76190476, 2.52777778, 2.17857143,
       2.17857143, 2.52777778, 2.17857143, 0.02857143, 2.375     ,
       2.        , 2.52777778, 2.375     , 0.02857143, 0.33333333,
       2.        , 2.52777778, 2.17857143, 0.02857143, 0.02857143,
       0.02857143, 2.52777778, 2.52777778, 2.        , 2.375     ,
       0.33333333, 2.52777778, 2.17857143, 0.02857143, 2.17857143,
       2.        , 0.02857143, 0.02857143, 2.375     , 2.        ,
       0.02857143, 2.375     , 2.52777778, 2.        , 2.52777778,
       0.02857143, 2.        , 2.52777778, 0.02857143, 2.52777778,
       0.02857143, 2.76190476, 2.17857143, 2.52777778, 2.52777778,
       2.76190476, 0.02857143, 2.52777778, 0.02857143, 2.375     ,
       0.33333333, 2.        , 0.02857143, 0.02857143, 0.33333333,
       2.        , 2.52777778, 0.33333333, 2.17857143, 2.76190476,
       2.        , 2.52777778, 0.02857143, 2.76190476, 2.375     ,
       2.375     , 0.02857143, 2.17857143, 0.33333333, 2.76190476,
       2.17857143, 2.76190476, 2.52777778, 0.02857143, 2.        ,
       2.17857143, 2.        , 2.52777778, 0.02857143, 0.33333333,
       2.        , 0.33333333, 2.17857143, 2.52777778, 0.33333333,
       2.17857143, 0.33333333, 2.76190476, 2.375     , 2.52777778,
       2.17857143, 0.33333333, 2.        , 0.33333333, 0.02857143,
       2.52777778, 2.76190476, 2.76190476, 2.        , 0.02857143,
       2.52777778, 2.17857143, 2.375     , 2.52777778, 0.02857143,
       0.33333333, 0.33333333, 2.375     , 2.76190476, 2.375     ,
       2.52777778, 2.        , 2.375     , 2.76190476, 2.375     ,
       2.        , 2.        , 2.        , 2.        , 2.17857143,
       0.02857143, 2.17857143, 2.17857143, 0.33333333, 2.76190476,
       2.        , 2.        , 0.33333333, 0.02857143, 2.52777778,
       2.76190476, 2.        , 2.52777778, 2.76190476, 0.02857143,
       0.02857143, 2.52777778, 2.375     , 2.52777778, 2.76190476,
       0.02857143, 0.33333333, 2.52777778, 2.375     , 2.        ,
       0.02857143, 2.17857143, 2.17857143, 2.375     , 2.52777778,
       2.375     , 2.52777778, 2.        , 2.375     , 2.        ])

In [ ]:
y_pred_test_new_new = new_model.predict(x_test)
y_pred_test_new_new

array([2.17857143, 2.52777778, 2.76190476, 2.375     , 0.33333333,
       2.        , 0.33333333, 0.02857143, 2.52777778, 2.        ,
       2.17857143, 2.52777778, 0.02857143, 2.        , 0.02857143,
       0.02857143, 0.33333333, 2.17857143, 2.52777778, 0.02857143,
       2.76190476, 2.17857143, 2.375     , 2.52777778, 2.375     ,
       0.02857143, 2.52777778, 2.375     , 2.76190476, 2.76190476,
       2.17857143, 2.        , 2.76190476, 2.375     , 2.52777778,
       0.02857143, 2.        , 0.33333333, 0.02857143, 2.        ,
       2.52777778, 0.02857143, 2.17857143, 2.52777778, 0.33333333,
       2.        , 2.        , 2.17857143, 0.02857143])

In [ ]:
#check the accuracy
r2_train_new_new = r2_score(y_train,y_pred_new_new)
r2_train_new_new

0.7887454546331395

In [ ]:
r2_test_new_new = r2_score(y_test,y_pred_test_new_new)
r2_test_new_new

0.8330326532402093