<a href="https://colab.research.google.com/github/sanjay-MGR/Machine-Learning-basic-/blob/main/Introduction_to_Machine_Learning_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Introduction to machine learning : it is a subset of AI

#simple model building and test in machine learing

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = sns.load_dataset('iris')

In [ ]:
data.head(2)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [ ]:
data.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
x = data.drop('species',axis=1)
x.head(2)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2

In [ ]:
y = data['species']
y.head(2)

0    setosa
1    setosa
Name: species, dtype: object

In [ ]:
#import train_test_split
#train data 80%
#test data 20%
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
#import model
from sklearn.svm import SVC

In [ ]:
#model build
model = SVC()
model

SVC()

In [ ]:


#fit model
model.fit(x_train,y_train)

SVC()

In [ ]:
#Predict values
y_pred = model.predict(x_test)
y_pred

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa'], dtype=object)

In [ ]:
#acuuracy test
from sklearn.metrics import accuracy_score
acs = accuracy_score(y_test,y_pred)
acs

1.0

In [ ]:
# load datasets
data1 = sns.load_dataset('mpg')
data1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [ ]:
df1 = data1[['mpg','displacement','horsepower','acceleration']]
df1.head(5)

    mpg  displacement  horsepower  acceleration
0  18.0         307.0       130.0          12.0
1  15.0         350.0       165.0          11.5
2  18.0         318.0       150.0          11.0
3  16.0         304.0       150.0          12.0
4  17.0         302.0       140.0          10.5

In [ ]:
df1.isna().sum() #check null values

mpg             0
displacement    0
horsepower      6
acceleration    0
dtype: int64

In [ ]:
df1['horsepower']=df1['horsepower'].fillna(df1['horsepower'].mean())

/tmp/ipykernel_5055/377263257.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['horsepower']=df1['horsepower'].fillna(df1['horsepower'].mean())

In [ ]:
df1.isna().sum()

mpg             0
displacement    0
horsepower      0
acceleration    0
dtype: int64

In [ ]:
#split data into X and Y
X = df1.drop('mpg',axis=1)
X.head(5)

   displacement  horsepower  acceleration
0         307.0       130.0          12.0
1         350.0       165.0          11.5
2         318.0       150.0          11.0
3         304.0       150.0          12.0
4         302.0       140.0          10.5

In [ ]:
y = df1['mpg']
y.head(5)

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=42)

In [ ]:
#import model
from sklearn.linear_model import LinearRegression

In [ ]:
#build model
ml = LinearRegression()
ml

LinearRegression()

In [ ]:
#fit the model
ml.fit(x_train,y_train)

LinearRegression()

In [ ]:
#predict the value
y_pred_train = ml.predict(x_train)
y_pred_test = ml.predict(x_test)

In [ ]:
#find accuracy
from sklearn.metrics import r2_score

In [ ]:
r2_score_train = r2_score(y_train,y_pred_train)
r2_score_train

0.6668868457129669

In [ ]:
r2_score_test = r2_score(y_test,y_pred_test)
r2_score_test

0.6786377089083508